### ISSUE TITLE
Ayuda en error libminizip-1.dll

### ISSUE THREAD

**Issue by masterjmdv** [teamQPM/qpm#1]
Hola Fernando, disculpa si me equivoque de lista.

He actualizado OOHG a la ultima versión (instalado desde cero)  en windows 8.1 64 bits

Uso oohg+ mingw+ qpm a 32bit.

Al  querer compilar una aplicación me da el error libminizip-1.dll
 (la ejecución de código no puede continuar porque no se encontró libminizip-1.dll. Este problema se puede solucionar reinstalando el programa).

Me pasa con distintas versiones de qpm ej 5.05.05 y con la ultima QPM 5.05.16 tb

De echo estoy tratando de compilar de los samples\zip el s0002.prg y me arroja el error

No tengo libreria adicional en la solapa LIB.

En que estoy fallando?

Saludos.

Juan Manuel Del Valle
[path LIBRERIAS.docx](https://github.com/teamQPM/qpm/files/4816147/path.LIBRERIAS.docx)

**Comment by fyurisich** [comment]
Hola, Juan Manual: por favor prueba agregando
-static 
en el campo Extra Link Params de la pestaña Log Build Process.
Saludos, Fernando.

**Comment by masterjmdv** [comment]
Impecable....
Con esa clausula que estoy haciendo puntualmente...?

**Comment by fyurisich** [comment]
Le indicas al compilador C que agregue las librerías a tu EXE para que no las tenga que buscar en forma dinámica.

**Comment by masterjmdv** [comment]
Mil gracias.... como siempre... un lujo
