### ISSUE TITLE
Please, I humbly request your help

### ISSUE THREAD

**Issue by masterjmdv** [teamQPM/qpm#2]
** Describe your request **
Write a clear and concise description of your request.
Explain what is happening and what you expected to happen.

** How to reproduce and test **
Add a project (.QPM file, sources, resources, etc.) that shows what you are trying to do or achieve.
Detail the steps to build, run, and test.

** Additional Information **
Add any additional information (including screenshots) to help explain your request.

**Comment by fyurisich** [comment]
No information provided.
