### ISSUE TITLE
Extra Link Parameter

### ISSUE THREAD

**Issue by pcmodula** [teamQPM/qpm#71]
Hi Fernando, i have tested today the latest build (5.5.20)
i incountered, some bug adding Strip Exe and Allow multiple definitions.
I do not use Allow multiple definition checkbox, but manually enter -Wl,--allow-multiple-definition, now if choice Strip exe
-s is added with success, but i dont use extra links and check the two option, i obtain -Wl,--allow-multiple-definition-s each time press F4 (note that -s is entered without the space and throws error).
This happens by compiling in 64bit with extended minigui and Mingw.
I hope I explained myself.
The -s option is very interesting!
Rds Pcmodula

**Comment by fyurisich** [comment]
Fixed. See a6e4f2dac1e534195c209eca6d605cc61439b363

**Comment by fyurisich** [comment]
Download new exe from [here](https://github.com/teamQPM/qpm/raw/main/QPM.exe)
