### ISSUE TITLE
Incorrect switch setting

### ISSUE THREAD

**Issue by pcmodula** [teamQPM/qpm#74]
Hi Fernando, when switch from Borland to mingw the checkbox Strip EXE and Allow Multiple definitions aren't selectable.
I Must save and reopen Project options for add these switch.
Happy 2021
Pcmodula

**Comment by fyurisich** [comment]
Fixed. See ce9e763f744d739b1cafb277e721696026dfd97e
Download new exe from [here](https://github.com/teamQPM/qpm/raw/main/QPM.exe)
